<h2>Rénitialisation du mot de passe</h2>

<form action="../controller/reset_password.php" method="post" class=""> 

<label for="reset_password">Votre nouveau mot de passe</label><br>
<input type="text" name="reset_password" class="" id="reset_password"> <br><br>

<label for="confirm_reset_password">Confirmé votre nouveau mot de passe</label><br>
<input type="text" name="confirm_reset_password" class="" id="confirm_reset_password"> 
<br><br>
<input type="submit" value="Réinitialisé le mot de passe" class="">

</form> 

<?php 

if(array_key_exists('error', $_SESSION)){
    foreach($_SESSION['error'] as $e){
    ?>
    <strong><?= $e; ?></strong>
    <?php 
    }
}

?> 

<?php unset($_SESSION['error']); ?>