<main>
<h1>Découvrir l'autogire</h1>

    <section class="container section-three">
        <h3>Les avantages du vol en autogire</h2>
        <div class="row ">
        
        </div>
        <div class="row ">
        
        </div>
        <div class="row ">
        
        </div>          
    </section>
    <section class="container">
        <aside>
            <img src="" alt="">


        </aside>
        <div class="article">
        giro1 Le Ela 10 Eclipse est le fleuron de la marque Ela Aviacion. C’est assurément le meilleur autogire caréné du marché ! Notre engin date de 2012, il cumule 3 000 heures de vol. L’autogire est particulièrement adapté pour le vol en montagne grâce à sa stabilité.  Il est également l’appareil le plus silencieux autorisé chez nos voisins suisses. Grâce à sa cabine fermée vous pouvez embarquer en toute sécurité et surtout en restant bien au chaud.
        </div>
    
    </section>
    <section class="container">
       
        <div  class="article">
        C’est le rotor principal de l’autogire (l’hélice sur le toit) qui assure la portance de l’engin. C’est grâce à lui que l’autogire se maintient en l’air. Et c’est le rotor arrière qui permet d’avancer. Cette conception permet de voler même lorsqu’il y a du vent et de décoller et atterrir sur de courtes distances.  Contrairement à un hélicoptère, l’autogire ne peut pas décrocher, c’est-à-dire que son rotor ne peut pas s’arrêter brutalement. Pas de risque d’accident !
        </div>
        <aside>
            <img src="" alt="">


        </aside>
    
    </section>



    <section class="image image-two">
        <a href="#" class="secondary-button call-to-action" role="button"> 
            Déroulé d'un vol 
        </a>  
    </section>

    <section class="container">
        <h2>Notre pilote</h2>
        <div class="row">
            <aside>
                <img src="" alt="">
            </aside>
            <div class="article">
                Jean-Pierre Lafon sera votre pilote pour ce survol des Hautes-Alpes.
                Passionné de vol depuis toujours, il a d'abord passé unbrevet de pilote d'ULM pendulaire avant de se tourner vers l'autogire, qui offre plus de possibilités dans nos montagnes. Cumulant aujourd'hui 3000 heures de vol, il connaît parfaitement la région et sera votre guide!
            </div>
        </div>
    
    </section>




    <section class="image image-two">
        <a href="#" class="secondary-button call-to-action" role="button"> 
            Réserver un vol 
        </a>  
    </section>




</main>