<main>

        <section class="container">
            <h2>Baptêmes de l'air et vols en autogire dans les Hautes alpes</h2>
            <p>Le vol en autogire (proche du parapente et de l'ULM) est le meilleur moyen de découvrir les Hautes-alpes depuis le ciel, territoire à la croisée de la Provence et des montagnes. Laissez-vous tenter!</p>
        </section>

        <section class="image image-one">
            <a href="#" class="secondary-button" role="button"> 
                Qu'est-ce qu'un autogire? 
            </a>
        </section>

        <section class ="container section-two">
            <h2>Nos vols</h2>
            <div class="row space marg"> 
                <a href="" class="card">
                    <h3 class="card-img-top item-primary">Le Baptême</h3>
                    <p class="card-body">En savoir plus</p>
                </a>
                <a href="" class="card">
                    <h3 class="card-img-top item-primary">La Balade</h3>
                    <p class="card-body">En savoir plus</p>
                </a>
            </div>
            <div class="row space marg"> 
                <a href="" class="card">
                    <h3 class="card-img-top item-primary">La Randonnée</h3>
                    <p class="card-body">En savoir plus</p>
                </a>
                <a href="" class="card">
                    <h3 class="card-img-top item-primary">L'Evasion</h3>
                    <p class="card-body">En savoir plus</p>
                </a>

            </div>
        </section>

        <section class="container section-three">
            <h2>Envie de (se) faire plaisir?</h2>
            <div class="row space">
                <div class="column">
                    <img src="../medias/img/treasure-map.svg" alt="" class="icone">
                    <a href="#" class="primary-button" role="button"> 
                        Le vol à la carte 
                    </a>
                </div>
                <div class="column">
                    <img src="../medias/img/cadeau.svg" alt="" class="icone">
                    <a href="#" class="primary-button" role="button"> 
                        Le vol cadeau 
                    </a>
                    
                </div>
            </div>
        </section>

        <section class="image image-two">
            <a href="#" class="secondary-button call-to-action" role="button"> 
                Déroulé du vol 
            </a>  
        </section>

    </main>