<main>
<h1>Nos vols</h1>
<p>Réserveez votre vol parmi notre sélection. Si vous avez une demande particulière, nous nous adapterons</p>

    <section class="container">
        <div class="row">
            <aside>
                <img src="../medias/img/cadeau.svg" alt="">
            </aside>
            <div class="article">
                <div>
                    <h2>Le Baptême</h2>
                    <div>
                        Embarquez pour une balade aérienne d’une vingtaine de minutes. Au départ d’Aspres-sur-Buëch, vous aurez un point de vue inédit et magnifique sur toute la vallée du Buëch et ses montagnes. C’est un cadeau idéal pour vos proches !
                            
                    </div>

                </div>
                <div class="row">
                    <i class="fa fa-euro-sign"></i> 
                    <i class="fa fa-clock"></i>
                    <a href="#" class="primary-button" role="button"> 
                        Réserver 
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="container">
        <div class="row">
            <div class="article" >
                <h2>La Balade</h2>
                <div>
                    Vous découvrirez la Provence et ses paysages si particuliers pendant ce circuit, plus long qu’un baptême. Direction Sisteron et sa splendide citadelle, à la croisée des Hautes-Alpes et des Alpes de Haute Provence.  
                </div>
                <div>
                    <i class="fa fa-euro-sign"></i> 
                    <i class="fa fa-clock"></i>
                    <a href="#" class="primary-button" role="button"> 
                        Réserver 
                    </a>
                </div>
            </div>
            <aside>
                <img src="" alt="">
            </aside>
        </div>
    </section>

    <section class="container">
        <div class="row">
            <aside>
                <img src="" alt="">
            </aside>
            <div class="article">
                <h2>La Randonnée</h2>
                <div>
                    Frôlez les sommets des Alpes du Sud ! Grâce à l’autogire, vous avez tout le plaisir de la montagne, sans vous fatiguer avec cette randonnée. Pensez à prendre votre appareil photo : on croise parfois des chamois !
                </div>
                <div>
                    <i class="fa fa-euro-sign"></i> 
                    <i class="fa fa-clock"></i>
                    <a href="#" class="primary-button" role="button"> 
                        Réserver 
                    </a>
                </div>
            </div>
        </div>
        
    </section>

    <section class="container">
        <div class="row">
            <div class="article">
                <h2>L’Evasion</h2>
                <div>
                    Préparez-vous à découvrir les plus beaux paysages des Hautes-Alpes ! Pendant ce vol, vous remonterez la Vallée du Buëch, jusqu’à Gap d’où vous apercevrez le Champsaur avant de survoler le lac de Serre-Ponçon, magnifique vu du ciel !
                </div>   
                <div>
                    <i class="fa fa-euro-sign"></i> 
                    <i class="fa fa-clock"></i>
                    <a href="#" class="primary-button" role="button"> 
                        Réserver 
                    </a>
                </div>
            </div>
            <aside>
                <img src="" alt="">
            </aside>
        </div>
    </section>


    <section class="image image-two">
        <a href="#" class="secondary-button call-to-action" role="button"> 
            Déroulé du vol 
        </a>  
    </section>

     <section class="container">
        <div clas="row">
            <aside>
                <img src="../medias/img/treasure-map.svg" alt="">
            </aside>
            <div class="article">
                <h2>Le vol à la carte</h2>
                <div>
                    Si vous avez une demande particuliére, n'hésitez pas à nous en parler. Giro JP s'adaptera au mieux à vos envies
                </div>
                <a href="#" class="primary-button" role="button"> 
                    Réserver 
                </a> 
        </div>
    
    </section>

    <section class="container">
        <div clas="row">
            <div class="article">
                <h2>Le vol cadeau</h2>
                <div>
                    Tous nosvols sont évidemment disponibles en bons cadeaux ! N'hésitez pas à nous le présicer lors de votre réservation!
                </div>  
                <a href="#" class="primary-button" role="button"> 
                    Réserver 
                </a> 
            </div>
           
            <aside>
                <img src="../medias/img/cadeau.svg" alt="" class="icone">
            </aside>
         </div>
    </section>

    <section class="container">
        <div>
            Attention Giro Jpse réserve le droit d'annuler un vol même au dernier moment. L'autogire ne permet d'embarquer qu'une seule personne à la fois. Paiement par chèque ou espèces.
        </div>
    </section>



</main>