<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="<?= $meta_description; ?>">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800,900|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet"> 
    <link rel="stylesheet" href="../sass/css/style.css">
    <title><?= $title; ?></title>
  </head>
  <body>
   
  <!-- Header avec conditions -->

    <?php include "../vew/$vew"; ?>

  <!-- Footer -->

  <!-- Script JS --> 
  </body>
</html>
